### ISSUE TITLE
Issues with the camera pose in lidar fusion.

### ISSUE THREAD

**Issue by Siyeong-Lee** [xtreme1-io/xtreme1#157]
- Currently, I am inputting consecutive frames into one dataset, and I am representing all objects based on the coordinate system of the first frame.

1. When setting `rowMajor=False` and inserting the camera pose as mentioned in the documentation, it appears to be correct when inserted in the opposite way.

2. When describing the pose of a camera in global position, it appears as if the camera is fixed and not moving, as if it is locked to the first frame.
  *  In which coordinate system should camera poses be specified to appear correctly?

Could I ask you to validate the logic for this?

**Comment by nicozhan** [comment]
1. Since these are consecutive frames, each frame must have its own coordinate system unless they have already been aligned to the coordinate system of the first frame in advance.

2. Generally, **rowMajor** is set to True, meaning that the extrinsic matrix is flattened in the order from left to right and from top to bottom, so that the last 4 values are guaranteed to be 0, 0, 0, 1. If you set rowMajor to False, make sure to adjust the flattening order accordingly. In any case, the flattening order and rowMajor should not contradict each other.

The extrinsic matrix represents the affine transformation matrix from the point cloud coordinate system to the camera coordinate system.

**Comment by Siyeong-Lee** [comment]
Thanks @nicozhan
2.  Contrary to what you said, it appears normal when I input it as follows. Can you comment on this?
```
{'camera_internal': {'fx': 1446.039591993387, 'fy': 1446.4136700881195, 'cx': 1213.5322911351127, 'cy': 989.9615596789163}, 'width': 2448, 'height': 2048, 'camera_external': [-0.0015522654730973525, 0.02732957339658133, -0.999625272234481, -1.813375734679572, 0.9999786320157491, 0.006390331930148412, -0.001378103672509482, 0.01568770145447134, 0.006350274309877384, -0.999606051440157, -0.027338908910304237, 1.5066161583340807, 0.0, 0.0, 0.0, 1.0], 'rowMajor': False}
```
