### ISSUE TITLE
How can I update new version with keep our dataset uploaded?

### ISSUE THREAD

**Issue by jotamotk** [xtreme1-io/xtreme1#209]
Dear Xtreme1 team. 
I saw the new release version v0.9. How can I update new version with keep our dataset uploaded?

**Comment by jaggerwang** [comment]
Sorry, due to table structure adjustments between versions, on-site upgrades are currently not supported. You can only export the results from the original instance and then import them into a new instance.
In addition, currently there is no support for exporting data files. You need to merge the exported annotation results with the local data files before importing them into a new instance. We will soon support exporting data files.
