### ISSUE TITLE
1GB Upload limit

### ISSUE THREAD

**Issue by MaxPRon** [xtreme1-io/xtreme1#219]
Hi :)

I'm using Xtreme v0.9 locally on my workstation and want to label a Lidar Fusion Dataset.

When uploading a dataset it gets stuck at 0% pending (see screenshot)

![image](https://github.com/xtreme1-io/xtreme1/assets/17144445/ce23ad32-5c23-4cf0-9fb1-4b1594b99a0f)

From the cloud version I know that there is a 1GB limit for the upload. Does this also apply when running the annotation tool locally ?

I tried it also with a < 1GB dataset and it works. So I assume there is this limitation even though the tool doesn't directly complain.

Is there a way around this when running the tool locally ?

Any help is appreciated :)

Thanks a lot already!

**Comment by jaggerwang** [comment]
We have already adjust the nginx body size limit to 1TB in this PR #220, but at present, we are adopting a simple overall transmission method. Due to the memory limit of the browser, you can only transfer about 2GB of files. We plan to optimize the upload here for streaming upload in the future to break through the memory limit of the browser.

**Comment by MaxPRon** [comment]
@jaggerwang Understood! Thanks a lot for the reply
