### ISSUE TITLE
How to install for web?

### ISSUE THREAD

**Issue by lumax90** [xtreme1-io/xtreme1#260]
Hi, first of all thank you for this awesome tool. 

Im trying to install it for web (on AWS EC2) but installation tru docker somehow stuck at some point Idk what is the problem. Is there any guide for how to install on web server? (ip configuration etc)

Also when I start Xtreme1 on my local computer, its quite different from cloud version. is this on purpose(because of commercial uses) or theres new updates that will also come to github version? (if Im not wrong cloud version is v1.0 but github version is v0.9.1)

for the last question. as I saw popular export options are not available at this moment? (like coco, kitti etc) when do you plan to add this export options to xtreme1? this features also avialable on the cloud version if Im not wrong. thank you.

**Comment by jaggerwang** [comment]
We use the Docker container to deploy, thanks to its cross-platform characteristics, whether it is locally or on the server, the deployment method is consistent. If you deploy to the cloud server, you need to configure the external network IP to the server, or use a load balanner to forward the external request. The local port is 8190, that is, the service binding port of the Docker Nginx container on the host.

The open source version only contains the basic functions required by individual or small-scale data labeling. If you need more advanced features, you can use cloud services, which also provides free versions. Due to the limited energy, our focus is still on cloud services. The function of open source can only take time to maintain, and there is no complete implementation plan for the time being right now.
